version: "3"
networks:
  cthulhu_network:
    driver: bridge

volumes:
  pgdata:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=developer
      - POSTGRES_USER=developer
      - POSTGRES_DB=cthulhu
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - cthulhu_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=developer@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=developer
    depends_on:
      - postgres
    networks:
      - cthulhu_network

  service:
    build:
      context: .
    image: api_service
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - cthulhu_network
    command: sh -c "npm run migrate:latest && npm run start:dev"
    env_file:
      - .env